# app/modules/clients/application/ports/repository.py
import uuid
from typing import Protocol

from app.modules.clients.domain.entities import Client, NewClient, UpdateClient


class ClientsRepositoryProtocol(Protocol):
    async def get_by_id(self, id_: uuid.UUID) -> Client: ...
    async def get_by_id_or_none(self, id_: uuid.UUID) -> Client | None: ...
    async def get_by_document_or_none(self, document: str) -> Client | None: ...
    async def create(self, create_command: NewClient) -> Client: ...
    async def update(self, id_: uuid.UUID, update_command: UpdateClient) -> Client: ...
    async def delete(self, id_: uuid.UUID) -> None: ...
