"""add inf_dps to recurrences

Revision ID: 61e998947886
Revises: c4135b600b94
Create Date: 2026-06-20 12:34:43.762325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61e998947886'
down_revision: Union[str, Sequence[str], None] = 'c4135b600b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurrences', sa.Column('inf_dps', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurrences', 'inf_dps')
    # ### end Alembic commands ###
