"""add_clients_table

Revision ID: 701da3b7d176
Revises: cd3a73a41c66
Create Date: 2026-06-14 11:52:46.363208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701da3b7d176'
down_revision: Union[str, Sequence[str], None] = 'cd3a73a41c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('municipal_registration', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('zip_code', sa.String(length=8), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=60), nullable=True),
    sa.Column('complement', sa.String(length=156), nullable=True),
    sa.Column('neighborhood', sa.String(length=60), nullable=True),
    sa.Column('ibge_city_code', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_index('ix_clients_document', 'clients', ['document'], unique=True)
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_name', table_name='clients')
    op.drop_index('ix_clients_document', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
