"""empty message

Revision ID: c4135b600b94
Revises: fd9821844ad5
Create Date: 2026-06-15 20:39:12.603041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4135b600b94'
down_revision: Union[str, Sequence[str], None] = 'fd9821844ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recurrence_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('n_dps', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('nf_number', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('xml_sent', sa.Text(), nullable=True),
    sa.Column('xml_response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('emission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrences.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurrence_id', 'scheduled_date', name='uq_invoice_recurrence_date')
    )
    op.create_index('ix_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.create_index('ix_invoices_status_scheduled_date', 'invoices', ['status', 'scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_status_scheduled_date', table_name='invoices')
    op.drop_index('ix_invoices_client_id', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
