"""add_emission_counters

Revision ID: fd9821844ad5
Revises: 8e7fe2df248e
Create Date: 2026-06-14 12:11:59.760898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9821844ad5'
down_revision: Union[str, Sequence[str], None] = '8e7fe2df248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serie', sa.String(length=5), nullable=False),
    sa.Column('last_n', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emission_counters')
    # ### end Alembic commands ###
